export const DYNAMIC_REPEATER = "DYNAMIC_REPEATER";

export const GET_REQUEST = `${DYNAMIC_REPEATER}/GET_REQUEST`;
export const SET_DATA = `${DYNAMIC_REPEATER}/SET_DATA`;
export const RESET_STATE = `${DYNAMIC_REPEATER}/RESET_STATE`;
