export const API_URL = `account/forgotpassword`;

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_REQUEST = `${FORGOT_PASSWORD}/FORGOT_PASSWORD_REQUEST`;
export const FORGOT_PASSWORD_STATUS = `${FORGOT_PASSWORD}/STATUS`;
export const FORGOT_PASSWORD_IDLE = `${FORGOT_PASSWORD}/IDLE`;
export const FORGOT_PASSWORD_SENT = `${FORGOT_PASSWORD}/SENT`;
